- gatsby/src/components/main-background/main-background.module.scss
W/o having the minimal image height its bottom can be in the middle of the title text, which decreases title readability.
> improved title readability on a mobile platform

- gatsby/src/components/main-background/main-background.module.scss
Minimal height of the background image increased and proportional resizing added to correctly fill in title background even in case of the listing pages containing breadcrumbs in the header
> increased background minimal height

- gatsby/src/components/search-results/index.tsx
- gatsby/src/components/search-results/search-results.module.scss
- gatsby/src/components/search-results/search-results.module.scss.d.ts
- gatsby/src/components/search-results/search-results.tsx
- UI for search results
- consumes data like:
```
results = [
{
title: 'title',
href: 'url',
text: 'description'
},{
...
}
]
```
It might be tweaked for the data available.
Didn't prepare breadcrumbs, they're part of different ticket. Can be added later.
Couldn't do last check, my local build is failing and i don't have space to fix it at the moment.
> feat(gatsby): add UI component for search results

- gatsby/assets/scss/design-system/base/_master.scss
external link icon displayed as pseudo `::after` instead of `::before`
Not sure if this is the right file to make the change or we should rather override the design system..?
Solves:
https://trello.com/c/uVTwPnQW/214-pati%C4%8Dka-ikonka-extern%C3%ADho-odkazu-zarovnat-s-prvn%C3%ADm-%C5%99%C3%A1dkem
> gatbsy/fix: external link icon displayed as pseudo after instead of before

- gatsby/src/components/measure-detail/index.tsx
- gatsby/src/components/measure-detail/measure-detail.tsx
- gatsby/src/components/situation-detail/situation-detail.module.scss.d.ts
- gatsby/src/components/situation-detail/situation-detail.scss.d.ts
- gatsby/src/components/situation-detail/situation-detail.tsx
- gatsby/src/components/topic-detail/index.tsx
- gatsby/src/components/topic-detail/topic-detail.module.scss
- gatsby/src/components/topic-detail/topic-detail.module.scss.d.ts
- gatsby/src/components/topic-detail/topic-detail.tsx
- gatsby/src/templates/lists/measures.tsx
- gatsby/src/templates/lists/situations.tsx
- gatsby/src/templates/measures/page.tsx
- gatsby/src/templates/situations/page.tsx
- using GraphQL fragments for better data collocation + TS types (up until now it worked mainly because of aliases)
- separated SituationDetail and MeasureDetails as both use different data
- created TopicDetail for the similiar parts of Situation and Detail
- removed several `any`s from the code (some data were previously actually missing - not fetched from graphql)
> gatsby - Measure and Situation component separation

- gatsby/src/components/measure-detail/measure-detail.tsx
- gatsby/src/components/subtitle/index.tsx
- gatsby/src/components/subtitle/subtitle.module.scss
- gatsby/src/components/subtitle/subtitle.module.scss.d.ts
- gatsby/src/components/subtitle/subtitle.tsx
- gatsby/src/components/topic-detail/topic-detail.tsx
Added the norm to the Measure detail page.
Decided to make it part of the content, for some of the measures, especially with longer norms, it looked super weird to have it just under the H1 above the content.
This is my first PR into this project, not sure if I missed anything or not, so I'm open to any criticism :))
Not sure if there is a design somewhere, I just rolled with what my eyes told me.
> gatsby: Add subtitle to Measure detail page

- gatsby/src/templates/lists/measures.tsx
- gatsby/src/templates/lists/situations.tsx
* opraveno nesprávné české řazení na seznamu opatření a situací
* pokud se nemýlím, GraphQL neumí lokalizované řazení, použit tedy lokálně`Intl.Collator`
* plus opraveno nastavování HTML jazyka - použito přímo z page contextu
> fix: ordering of measures and situations now respects current locale

- gatsby/src/components/footer/footer.tsx
- gatsby/src/components/i18n/i18n.tsx
- gatsby/src/components/i18n/index.tsx
- now fetching `allBlockContentBasicContent` because gatsby requires a static query (no variables allowed)
- matching the language in the component itself (probably will need a better alternative instead of `gLang`, but it does the job now... in the future some language context, perhaps?)
> gatsby/fix: added translations to footer

- gatsby/src/components/list-card/list-card.tsx
- gatsby/src/components/list-card/measure-list-card.module.scss
- gatsby/src/components/list-card/measure-list-card.module.scss.d.ts
- gatsby/src/components/list-card/measure-list-card.tsx
Desktop styles for list-card component as per design here:
https://www.figma.com/file/9avjIglqc1VVc84zHIoLha/CovidPortal?node-id=1045%3A12637
> Gatsby: list-card desktop styles

- gatsby/src/templates/measures/list.tsx
- gatsby/src/templates/situations/list.tsx
* same problem as in #254 (GraphQL ordering without respected locale)
* https://covid-gov-cz-git-gatsby-fixdetail-list-ordering.ceskodigital.vercel.app/situace/kompenzace
> fix(gatsby): ordering on measures/situations detail lists

- .github/workflows/gatsby.yml
- gatsby/src/components/footer/footer.tsx
- gatsby/src/components/guide/guide.tsx
- gatsby/src/components/header/header-locale-select.tsx
- gatsby/src/components/header/header.tsx
- gatsby/src/components/marker/marker.tsx
- gatsby/src/components/measure-detail/measure-detail.tsx
- gatsby/src/components/measure-list/measure-list.tsx
- gatsby/src/components/related-measure/related-measure.tsx
- gatsby/src/components/situation-detail/situation-detail.tsx
- gatsby/src/components/situations-box/situation.tsx
- gatsby/src/components/situations-box/situations-box.tsx
- gatsby/src/layouts/default-layout.tsx
- gatsby/src/pages/404.tsx
- gatsby/src/templates/custom-page/custom-page.tsx
- gatsby/src/templates/lists/index.tsx
- gatsby/src/templates/lists/measures.tsx
- gatsby/src/templates/lists/situations.tsx
- gatsby/src/templates/measures/list.tsx
- gatsby/src/templates/measures/page.tsx
- gatsby/src/templates/situations/list.tsx
- gatsby/src/templates/situations/page.tsx
- gatsby/tsconfig.json
- added alias to generated graphql types: `@graphql-types` so it does not seem like a package
- running typescript check only after build so the `graphql-types.ts` file is ready
> Gatsby: graphql types CI

- gatsby/src/components/schema/schema.tsx
- gatsby/src/templates/custom-page/custom-page.tsx
- gatsby/src/templates/lists/index.tsx
- gatsby/src/templates/lists/measures.tsx
- gatsby/src/templates/lists/situations.tsx
- gatsby/src/templates/measures/list.tsx
- gatsby/src/templates/measures/page.tsx
- gatsby/src/templates/situations/list.tsx
- gatsby/src/templates/situations/page.tsx
fixes: https://trello.com/c/s2yeUM8j/271-ogurl-is-missing-slug-with-langcode
> Gatsby/fix: og url langcode

- gatsby/src/components/guide/guide-item.tsx
The fixed height is not necessary anymore as we truncate the text via `-webkit-line-clamp`
Fixes:
https://trello.com/c/SH1a1yEK/219-user-font-size
How to test:
I used this extension for Chrome: https://chrome.google.com/webstore/detail/a%20-fontsize-changer-lite/ckihgechpahhpompcinglebkgcdgpkil?hl=en
clicked through all of the app and other screens look pretty much ok.
> Gatsby/fix: removed the fixed height from guide elements to improve accessibility

- gatsby/src/layouts/default-layout.tsx
Please, take care when changing the `default-layout.tsx` component so we dont have to fix this for a third time already 😞
> Gatsby/fix: sticky footer on desktop back once again

- gatsby/assets/scss/design-system/base/_master.scss
Small issue with external icon underline fixed
fixes:
[https://trello.com/c/Z4uI7Q0O/250-opravit-vzhled-odkazu](https://trello.com/c/Z4uI7Q0O/250-opravit-vzhled-odkazu)
Test:
external link icon is not underlined - hovered or not
external link icon does not overflow on a next row and stays stick right after the last link word
> external link icon is no more underlined

- gatsby/config/gatsby-config.ts
added missing subset (although by the plugin docs it says its by default) 🤷‍♂️
> gatsby/fix: added latin-ext subset to roboto google font

- gatsby/config/create-pages.ts
- gatsby/src/templates/custom-page/custom-page.tsx
- gatsby/src/templates/measures/list.tsx
- gatsby/src/templates/measures/page.tsx
- gatsby/src/templates/situations/list.tsx
- gatsby/src/templates/situations/page.tsx
* https://trello.com/c/c3B2EPwD/249-zm%C4%9Bnit-identifik%C3%A1tor-pro-graphql-na-generovan%C3%BDch-str%C3%A1nk%C3%A1ch
* added `$langCode` to all queries asking for content from GraphQL (no more conflicts `/cookies` vs. `/en/cookies`)
> fix: Gatsby GraphQL queries now respect current language

- README.md
- gatsby/README.md
- gatsby/gatsby-source-drupal/gatsby-node.js
- gatsby/package.json
- by default now, when running `yarn dev` it will download the drupal data just once
- to get fresh drupal data basically just run `yarn dev:clean`, or set your env variable `SHOULD_REFRESH_DRUPAL_DATA` to `1` and have it refreshed every single time
- all of the steps to get new data are documented
Why?
- the data pull takes the most time for the dev version to compile and its rarely required to update them
> feat/gatsby: drupal data dev mode cache

- gatsby/assets/scss/custom-variables.scss
- gatsby/src/components/measure-detail/measure-detail.tsx
- gatsby/src/components/situation-detail/situation-detail.tsx
- gatsby/src/components/subtitle/subtitle.module.scss
- gatsby/src/components/topic-detail/topic-detail.module.scss
- gatsby/src/components/topic-detail/topic-detail.module.scss.d.ts
- gatsby/src/components/topic-detail/topic-detail.tsx
I have changed the styling to fit according to Figma. It is not possible to put the region and time marker below the heading since it is a part of the article so it would need to be parsed (I feel it is nonsense). Therefore I put it below the article as it is everywhere else.
Done: 
https://trello.com/b/XOOBy51q/covidgovcz
To test:
measure and situation details look more like in Figma.
> situation and measure detail as in figma styled

- gatsby/assets/scss/design-system/base/_variables.scss
- gatsby/src/components/last-update/index.ts
- gatsby/src/components/last-update/last-update.module.scss
- gatsby/src/components/last-update/last-update.module.scss.d.ts
- gatsby/src/components/last-update/last-update.tsx
- gatsby/src/components/measure-detail/measure-detail.tsx
- gatsby/src/components/situation-detail/situation-detail.tsx
- gatsby/src/components/topic-detail/topic-detail.tsx
The final result differs a bit according to the design in figma. It's because The design does not count with incredibly huge titles. In these cases, it would need special behavior and it does not make sense to have the last update next to the title for small titles and below for the long ones. So I put it right after.
Solves:
https://trello.com/c/u6QK295g/278-add-last-updated-info
To test:
Last update info displays on all measures & situations details.
> feat: last updated label

- gatsby/src/layouts/default-layout.module.scss
After merging https://github.com/cesko-digital/covid.gov.cz/pull/370
Fixes:
> gatsby/fix: background position fixed after using new logo (without beta badge)

- gatsby/src/components/guide/guide.module.scss
- gatsby/src/components/measure-list/measure.module.scss
fixes:
+ adds a bit of of bigger padding on desktop version for the guide
> gatsby/fix: desktop css enchancements

- gatsby/config/gatsby-node.ts
Problem:
- when using `yarn dev` where it does not need to redoownload fresh data every single run, it would removoe the site search index, therefore crashing the dev build
Solution:
- touch the existing search index, so its not garbagee collected when using cached gatsby data
> gatsby/feat: dev search index

- gatsby/src/layouts/default-layout.module.scss
Resolves bug with the main photo space of 1px from the left side of the screen.
https://trello.com/c/1ZigUX44/281-mezi-okrajem-str%C3%A1nky-a-obr%C3%A1zkem-je-1-pixel
> gastby/fix: Offset of main photo by 1 px from left

- gatsby/src/components/category-item-list/category-item-list.module.scss
- gatsby/src/components/measure-detail/measure-detail.tsx
- gatsby/src/components/situation-detail/situation-detail.tsx
Changes:
* `gatsby/src/components/category-item-list/category-item-list.module.scss` – measure category link color fixed (back button); it's minor fix of an issue I noticed; [check here](https://covid-gov-cz-git-gatsby-fixmeasure-version-source.ceskodigital.vercel.app/opatreni/maloobchod-sluzby/narizeni-pro-provozovatele-obchodu-provozoven-sluzeb) (zpět na aktuální opatření was yellow, now it's blue)
* `gatsby/src/components/measure-detail/measure-detail.tsx` – that's the reason of this PR; [check here](https://covid-gov-cz-git-gatsby-fixmeasure-version-source.ceskodigital.vercel.app/opatreni/skolstvi/omezeni-provozu-vysokych-skol)
* `gatsby/src/components/situation-detail/situation-detail.tsx` – I just added some padding 😄
> Gatsby fix measure version source

- gatsby/src/layouts/default-layout.module.scss
Fix for resizing of the main photo on mobile when focused on the search bar and keyboard is opened.
https://trello.com/c/vRxEnr8L/325-389-bug-mobile-image-resizes-when-search-in-focus-with-keyboard-opened
Resolves #389
> gatsby/fix: Main photo resizes on mobile on keyboard open

- gatsby/src/layouts/default-layout.module.scss
Fix for the case when the main photo overflows footer when the main content of the page is missing or is too short.
https://trello.com/c/8DFudfvs/320-obr%C3%A1zek-na-pozad%C3%AD-p%C5%99et%C3%A9k%C3%A1
> gastby/fix: Main photo overflows footer if content is too short

- drupal/web/modules/custom/covid/src/EventSubscriber/RequestEventSubscriber.php
- drupal/web/modules/custom/covid/src/Form/LicenseAgreementForm.php
- Nahoře v červeném textu místo "s licenčním dojednáním" dát "s licenčním ujednáním"
- V posledním odstavci místo "Vstupem do [editorského rozhraní]" dát "Vstupem do administrace Covid portálu"
- Třetí řádek od konce místo "M ezinárodní" dát "Mezinárodní"
> Drupal: Fix licence agreement text.

- gatsby/src/components/search-box/search-box.tsx
Focus on search query input after click triggering search if the input is empty.
> gatsby/fix: Disabled search on empty input with focus

- gatsby/src/components/search-results/search-results.tsx
Adds a link to the homepage breadcrumb in the search results
> gatsby/fix: Search results home breadcrumb link

- gatsby/assets/scss/design-system/components/_breadcrumbs.scss
Fixed breadcrumb overflow by overwriting white-space property set by text-truncate mixin (instead of changing text-truncate mixin to not cause bugs elsewhere)
Before             |  After
:-------------------------:|:-------------------------:
> gatsby/fix: breadcrumb overflow
