.github/workflows/gatsby.yml
gatsby/package.json

closes https://trello.com/c/GEoPUtk9/18-introduce-fe-validate-github-action

Introduce Github Action for Gatsby directory

---

gatsby/README.md
gatsby/gatsby-config.js
gatsby/locales/cz/translation.json
gatsby/locales/en/translation.json
gatsby/package.json
gatsby/src/components/hello.tsx
gatsby/src/pages/index.tsx
gatsby/yarn.lock

Closes https://trello.com/c/jtwkXhKN/30-ui-translations

gatsby: add Localization i18next

---

.github/workflows/php.yml

https://github.com/cesko-digital/covid.gov.cz/actions?query=workflow%3A%22PHP+Composer%22

Drupal: Remove gatsby deploy stage

---

.vscode/settings.json
gatsby/package.json
gatsby/src/components/button/button.tsx
gatsby/src/components/button/index.tsx
gatsby/yarn.lock

feat(FE): button component

---

README.md
gatsby/config/gatsby-browser.tsx
gatsby/config/gatsby-config.ts
gatsby/gatsby-config.js
gatsby/package.json
gatsby/src/hooks/useAnalytics.ts
gatsby/src/types/global.d.ts
gatsby/yarn.lock

closes https://trello.com/c/4bVyTw3b/35-setup-appinsights

introduce ApplicationInsight

---

gatsby/src/components/breadcrumb/breadcrumb.tsx
gatsby/src/components/breadcrumb/index.tsx

Added breadcrumb navigation component

feat(FE): Breadcrumb nav component

---

gatsby/src/components/gov-icon/gov-icon.tsx
gatsby/src/components/gov-icon/index.tsx

Added component for official government UI icons

feat(gov icons): gov icon component

---

README.md

Added quick links to Trello and frontend deployed on Vercel (master branch).

docs(readme): links added to README

---

gatsby/package.json

gatsby devserver poslouchajici na 0.0.0.0, tzn. jde se k nemu pripojit i odjinud nez ze zarizeni, kde bezi (napr. z mobilu pro testovani)

gatsby: listen on 0.0.0.0

---

gatsby/src/components/button/button.tsx
gatsby/src/components/gov-icon/gov-icon.tsx
gatsby/src/components/search-box/index.tsx
gatsby/src/components/search-box/search-box.tsx
gatsby/src/layouts/default-layout.tsx
gatsby/src/pages/index.tsx

feat(search box): search box component

---

gatsby/assets/ds/scss/base/_variables.scss
gatsby/src/components/content-box/content-box.module.scss
gatsby/src/components/content-box/content-box.tsx
gatsby/src/components/text-box/text-box.module.scss
gatsby/src/components/text-box/text-box.tsx
gatsby/src/pages/text.tsx

textpage = detail opatreni apod.

gatsby: textpage pro desktop

---

gatsby/config/gatsby-config.ts
gatsby/src/components/container/container.tsx
gatsby/src/components/row/row.tsx

Added common classes to purgeCSS config, added comment classes to components.

fix(purge css): config updated, classes added to comments

---

drupal/config/sync/core.entity_form_display.node.situation.default.yml
drupal/config/sync/core.entity_form_display.taxonomy_term.icons.default.yml
drupal/config/sync/core.entity_view_display.node.situation.default.yml
drupal/config/sync/core.entity_view_display.node.situation.teaser.yml
drupal/config/sync/core.entity_view_display.taxonomy_term.icons.default.yml
drupal/config/sync/core.extension.yml
drupal/config/sync/field.field.node.situation.field_ref_icon.yml
drupal/config/sync/field.field.taxonomy_term.icons.field_icon_code.yml
drupal/config/sync/field.field.taxonomy_term.icons.field_icon_file.yml
drupal/config/sync/field.field.taxonomy_term.icons.field_icon_set.yml
drupal/config/sync/field.storage.node.field_ref_icon.yml
drupal/config/sync/field.storage.taxonomy_term.field_icon_code.yml
drupal/config/sync/field.storage.taxonomy_term.field_icon_file.yml
drupal/config/sync/field.storage.taxonomy_term.field_icon_set.yml
drupal/config/sync/jsonapi_extras.jsonapi_resource_config.node--situation.yml
drupal/config/sync/jsonapi_extras.jsonapi_resource_config.taxonomy_term--icons.yml
drupal/config/sync/language.content_settings.taxonomy_term.icons.yml
drupal/config/sync/taxonomy.vocabulary.icons.yml
drupal/config/sync/views.view.icons.yml

Trello: https://trello.com/c/9Udu3qYX/69-icon-set

Drupal: Add configurable icons to Situation.

---

drupal/composer.json
drupal/composer.lock
drupal/config/sync/core.entity_form_display.user.user.default.yml
drupal/config/sync/core.extension.yml
drupal/config/sync/field.field.user.user.field_last_password_reset.yml
drupal/config/sync/field.field.user.user.field_password_expiration.yml
drupal/config/sync/field.storage.user.field_last_password_reset.yml
drupal/config/sync/field.storage.user.field_password_expiration.yml
drupal/config/sync/language/en/field.field.user.user.field_last_password_reset.yml
drupal/config/sync/language/en/field.field.user.user.field_password_expiration.yml
drupal/config/sync/password_policy.password_policy.nakit.yml
drupal/config/sync/password_policy.settings.yml

Enforce at least 10 chars length and 3 char groups.

Drupal: Add password policy.

---

drupal/config/sync/views.view.moderated_content.yml
drupal/config/sync/workflows.workflow.content.yml

Trello: https://trello.com/c/e4LDUwAD/89-workflow-enhancements

Drupal: Translate moderation states.

---

gatsby/config/gatsby-config.ts
gatsby/package.json
gatsby/yarn.lock

Replacing obsolete drupal multilingual plugin with the official drupal plugin.

Gatsby: Replace Drupal connector.

---

drupal/config/sync/block_content.type.basic_content.yml
drupal/config/sync/core.entity_form_display.block_content.basic_content.default.yml
drupal/config/sync/core.entity_view_display.block_content.basic_content.default.yml
drupal/config/sync/core.entity_view_mode.block_content.full.yml
drupal/config/sync/core.extension.yml
drupal/config/sync/editor.editor.basic.yml
drupal/config/sync/field.field.block_content.basic_content.field_b_content.yml
drupal/config/sync/field.storage.block_content.body.yml
drupal/config/sync/field.storage.block_content.field_b_content.yml
drupal/config/sync/filter.format.basic.yml
drupal/config/sync/jsonapi_extras.jsonapi_resource_config.block_content--basic_content.yml
drupal/config/sync/language.content_settings.block_content.basic_content.yml
drupal/config/sync/language/en/core.entity_view_mode.block_content.full.yml
drupal/config/sync/language/en/views.view.block_content.yml
drupal/config/sync/views.view.block_content.yml

Trello: https://trello.com/c/M9SonbWY/122-drupal-menus

Drupal: Add custom block type Content.

---

gatsby/src/components/measure-list/measure-list.tsx
gatsby/src/components/measure-list/measure.tsx
gatsby/src/components/situations-box/situation.module.scss
gatsby/src/components/situations-box/situation.tsx
gatsby/src/pages/index.tsx

Trello: https://trello.com/c/bgoMP0vn/71-missing-links

Gatsby: Add missing links to detail (measures, situations)

---

gatsby/config/create-pages.ts
gatsby/config/gatsby-config.ts
gatsby/src/pages/404.module.scss
gatsby/src/pages/404.module.scss.d.ts
gatsby/src/pages/404.tsx
gatsby/src/templates/custom-page/custom-page.tsx

feat: added custom pages logic, added 404 page

---

gatsby/src/components/looking-for-something/index.tsx
gatsby/src/components/looking-for-something/looking-for-something.module.scss
gatsby/src/components/looking-for-something/looking-for-something.module.scss.d.ts
gatsby/src/components/looking-for-something/looking-for-something.tsx

Two things:
1. Should the right arrow link somewhere? 🤔
2. I couldn't find the icon for phone so I used one for phone from material ui. Is it an issue?
Trello: https://trello.com/c/IgVYRGBL/105-looking-for-something-component

Gatsby: LookingForSomething component

---

gatsby/src/components/pagination/index.tsx
gatsby/src/components/pagination/pagination-button.module.scss
gatsby/src/components/pagination/pagination-button.module.scss.d.ts
gatsby/src/components/pagination/pagination-button.tsx
gatsby/src/components/pagination/pagination.module.scss
gatsby/src/components/pagination/pagination.module.scss.d.ts
gatsby/src/components/pagination/pagination.tsx

Added Pagination component. 
Not all styles are fully implemented, but we need to start implementing this component to other pages/components.

feat(pagination): pagination added

---

gatsby/src/components/header/header.module.scss

Having z-index 1, it's covered by the main content div

dropdown menu made visible on a mobile platform

---

gatsby/src/components/header/header-locale-select.tsx
gatsby/src/components/header/header.tsx
gatsby/src/components/list-card/list-card.tsx
gatsby/src/components/measure-list/measure-list.tsx
gatsby/src/components/situations-box/situations-box.tsx
gatsby/src/pages/text.tsx
gatsby/src/templates/custom-page/custom-page.tsx
gatsby/src/templates/situation/list.tsx

fixed all errors caused by checks

fix:fixed all errors

---

gatsby/assets/scss/design-system/components/_breadcrumbs.scss

Update based on the UI proposal

Link color of active breadcrumb updated

---

drupal/config/sync/core.base_field_override.node.notice.promote.yml
drupal/config/sync/core.base_field_override.node.notice.title.yml
drupal/config/sync/core.entity_form_display.node.notice.default.yml
drupal/config/sync/core.entity_view_display.node.notice.default.yml
drupal/config/sync/core.entity_view_display.node.notice.teaser.yml
drupal/config/sync/field.field.node.notice.field_notice_content.yml
drupal/config/sync/field.field.node.notice.field_notice_link.yml
drupal/config/sync/field.field.node.notice.field_valid_from.yml
drupal/config/sync/field.field.node.notice.field_valid_to.yml
drupal/config/sync/field.storage.node.field_notice_content.yml
drupal/config/sync/field.storage.node.field_notice_link.yml
drupal/config/sync/jsonapi_extras.jsonapi_resource_config.node--notice.yml
drupal/config/sync/language.content_settings.node.notice.yml
drupal/config/sync/node.type.notice.yml

Trello: https://trello.com/c/fxKxrGHs/41-content-type-notice

Drupal: Add Notice content type with GQL endpoint.

---

gatsby/src/templates/lists/index.tsx

https://cesko-digital.slack.com/archives/C01D8E49C1M/p1604610425141300?thread_ts=1604609321.140400&cid=C01D8E49C1M

Gatsby: currently hide alert at homepage

---

gatsby/config/gatsby-config.ts
gatsby/package.json
gatsby/src/components/category-item/category-item.tsx
gatsby/src/components/content-icon/content-icon.tsx
gatsby/src/components/content-icon/index.tsx
gatsby/src/components/situations-box/situation.module.scss
gatsby/src/components/situations-box/situation.tsx
gatsby/src/templates/lists/index.tsx
gatsby/src/templates/lists/measures.tsx
gatsby/src/templates/lists/situations.tsx
gatsby/yarn.lock

https://trello.com/c/E4H94IW5/150-list-of-categories-icons
- Added material-icons as font instead of npm library, because it's easier to use it this way with data coming from API
- Created ContentIcon component that is used for icons populated with API data

[WIP] Gatsby/feature/list of categories icons

---

gatsby/assets/scss/design-system/components/_breadcrumbs.scss

Reverts cesko-digital/covid.gov.cz#161

Revert "Link color of active breadcrumb updated"

---

gatsby/src/components/header/header.tsx
gatsby/src/components/looking-for-something/looking-for-something.tsx
gatsby/src/templates/custom-page/custom-page.tsx
gatsby/src/templates/lists/index.tsx
gatsby/src/templates/lists/measures.tsx
gatsby/src/templates/lists/situations.tsx

This reverts commit b6f63a0a76a7d89e216f6f33c411ec9cb6cedb0e, reversing
changes made to b3522e75e74fee5d3c53605391e50c41d8ecf67a.

fix: zachrana

---

README.md

Readme: Hide link to vercel.

---

.github/workflows/deploy.yml

This reverts commit 8a001c0977960fda1655996f8ad79957c5289f4e.

Revert "Ops: Add env variables for Gatsby. (#243)"

---

gatsby/assets/scss/custom-variables.scss
gatsby/src/components/header/header.module.scss
gatsby/src/components/header/header.tsx
gatsby/src/templates/situations/page.tsx

this is the most important commit of the repository

gatsby semicolon removed

---

.github/workflows/deploy.yml

~~Waiting for @radkoa for adding secret.~~

Ops: Fix scheduled runs and add Slack notifications

---

gatsby/src/layouts/default-layout.tsx

After https://github.com/cesko-digital/covid.gov.cz/pull/231 the footer became "not sticky" once again. This PR fixes that.

gatsby/fix: sticky footer

---

gatsby/src/components/marker/index.tsx
gatsby/src/components/marker/marker.tsx
gatsby/src/components/measure-detail/measure-detail.tsx
gatsby/src/components/related-measure/index.tsx
gatsby/src/components/related-measure/related-measure.module.scss
gatsby/src/components/related-measure/related-measure.module.scss.d.ts
gatsby/src/components/related-measure/related-measure.tsx
gatsby/src/components/situation-detail/situation-detail.tsx
gatsby/src/templates/situations/page.tsx

- added `RegionsMarker` and `TimeMarker` component
- added `RelatedMeasure` component
- removed some unnecessary data from Situations page and use `SituationDetail` fragment instead

gatsby/feat: related measures

---

drupal/config/sync/language.negotiation.yml
drupal/config/sync/user.role.editor.yml
drupal/config/sync/user.role.reviewer.yml

Trello: https://trello.com/c/5vcZDcOn/258-add-editor-permission-to-alter-url-alias-alias-slug

Drupal: Enable editor with option to change URL alias.

---

gatsby/config/create-pages.ts
gatsby/package.json
gatsby/src/components/header/header-locale-select.tsx
gatsby/src/components/header/header.tsx
gatsby/src/layouts/default-layout.tsx
gatsby/src/pages/404.tsx
gatsby/src/templates/custom-page/custom-page.tsx
gatsby/src/templates/lists/index.tsx
gatsby/src/templates/lists/measures.tsx
gatsby/src/templates/lists/situations.tsx
gatsby/src/templates/measures/list.tsx
gatsby/src/templates/measures/page.tsx
gatsby/src/templates/situations/list.tsx
gatsby/src/templates/situations/page.tsx

* PR is solving problem described in #198 (resetting URL after switching languages)
* refactored `create-pages.ts` to include language variants to page context (paired by `drupal_id`)
* `HeaderLocaleSelect` is now getting target URL from these variants
* found 51 nodes without English equivalent:
```
/situace/zamestnani/pravni-pomoc {}
/situace/socialni-situace/umrti-blizkeho-na-covid-19 {}
/situace/socialni-situace/exekuce-insolvence {}
/situace/socialni-situace/pravni-pomoc-socialni-situace {}
/situace/socialni-situace/osetrovne {}
/situace/socialni-situace/podpora-zamestnanosti {}
/situace/socialni-situace/ztrata-zamestnani-socialni-situace {}
/situace/kultura/vouchery {}
/situace/hoaxy/rousky {}
/situace/hoaxy/myty-o-nemoci-covid-19 {}
/situace/hoaxy/myty-o-erousce {} …
```

fix(gatsby): switching between page language variants (closes #198)

---

gatsby/src/components/schema/schema.tsx
gatsby/src/templates/lists/index.tsx

fixes:
https://trello.com/c/PtY27d7b/261-fix-homepage-ogtitle
and
https://trello.com/c/Ap3CFLrl/259-meta-data-for-better-sharing-and-serp

gatsby/fix: adjusted og title + added description and twitter image

---

gatsby/src/components/schema/schema.tsx
gatsby/src/templates/custom-page/custom-page.tsx
gatsby/src/templates/lists/measures.tsx
gatsby/src/templates/lists/situations.tsx
gatsby/src/templates/measures/list.tsx
gatsby/src/templates/measures/page.tsx
gatsby/src/templates/situations/list.tsx
gatsby/src/templates/situations/page.tsx

Edits of schema.org as discussed in https://trello.com/c/UnkM6kna/260-schemaorg

Gatsby: Edit of schema.org

---

drupal/web/modules/custom/covid/covid.install

This reverts commit db77d7de363eebc7b27b9c7961f2f148200c7866.

Revert "Drupal: Fix order of updates."

---

.github/workflows/gatsby.yml
gatsby/__tests__/__snapshots__/button.react.test.tsx.snap
gatsby/__tests__/alert.spec.tsx
gatsby/__tests__/button.react.test.tsx
gatsby/assets/scss/custom-variables.scss

- fixing some lint errors that got to master
- added config to run github actions for gatsby also on PR creation
BTW (i didnt know) we can use stylelint auto fixes as well - https://github.com/stylelint/vscode-stylelint/issues/35

gatsby/fix: typescript check and stylelint fixes

---

.github/workflows/gatsby.yml

gatsby/fix: github actions syntax to run hooks on PR

---

gatsby/config/gatsby-node.ts
gatsby/src/components/footer/footer.tsx
gatsby/src/layouts/default-layout.tsx

alert in the header is way too distracting + causes the mobile menu buggy
theres no need to have it that big, lets put it into the footer :)

fix: gatsby - moved build message to footer

---

gatsby/assets/scss/custom-variables.scss
gatsby/src/components/related-measure/related-measure.tsx

I also put the menu button back.

gatsby english measures links fixed

---

gatsby/src/components/schema/schema.tsx
gatsby/src/templates/lists/measures.tsx
gatsby/src/templates/lists/situations.tsx
gatsby/src/templates/measures/list.tsx
gatsby/src/templates/situations/page.tsx

Reverts cesko-digital/covid.gov.cz#351

Revert "feat: Gatsby: Additional edits of schema.org #327"

---

gatsby/src/components/schema/schema.tsx
gatsby/src/templates/custom-page/custom-page.tsx
gatsby/src/templates/measures/page.tsx
gatsby/src/templates/situations/page.tsx

Fix of build error caused by the wrong merge of "master" branch into original schema.org branch on PR https://github.com/cesko-digital/covid.gov.cz/pull/351.
Additional fix of `null` datePublished in some cases of measures pages.

fix: Gatsby: schema.org: fix of error in build caused by merge of "master" on PR #351

---

gatsby/src/components/schema/schema.tsx

- fixing error merged to master

fix: gatsby - added missing variable

---

gatsby/locales/cs/translation.json
gatsby/locales/en/translation.json

this PR just removes one useless folder ¯\\\_(ツ)\_/¯

gatsby refactor: unused locales folder removed

---

gatsby/src/components/schema/schema.tsx
gatsby/src/templates/situations/page.tsx

Return of some changes lost by error when merging "master" in PR #351 and then reverting it in #353
I hope that now it will merge as expected 🙂

feat: Gatsby: schema.org: return of lost changes in schemas

---

gatsby/src/components/schema/schema.tsx

- added meta noindex for vercel deploys

gatsby/fix: added meta noindex for vercel deploys

---

gatsby/src/components/guide/guide-item.module.scss
gatsby/src/components/guide/guide-item.module.scss.d.ts
gatsby/src/components/guide/guide-item.tsx

Grid buttons aligned. Basically, I display them in flex container with `align-self: flex-end` and `margin-top: auto`. 
Done:
https://trello.com/c/zNsjgjZd/296-align-grid-buttons

grid buttons aligned

---

gatsby/src/components/alert/alert.module.scss
gatsby/src/components/alert/alert.module.scss.d.ts
gatsby/src/components/alert/alert.tsx
gatsby/src/components/header/header.module.scss
gatsby/src/components/header/header.tsx

https://trello.com/c/k0G8J02i/318-banner-to-feed-data-from-translations

Gatsby/feat: alert

---

gatsby/src/components/header/header.module.scss

as the title says :) tested locally

gatsby/fix: increased english button switch so its visible on iphone x as well

---

gatsby/src/components/header/header.tsx
gatsby/src/components/i18n/translations.tsx
gatsby/src/pages/404.module.scss
gatsby/src/pages/404.module.scss.d.ts
gatsby/src/pages/404.tsx

- translated 404 page
- fixed `console.error` for when the translation does not exist, but its expected

Gatsby/feat: 404 translated

---

drupal/config/sync/core.entity_form_display.paragraph.pes_content.default.yml
drupal/config/sync/core.entity_view_display.paragraph.pes_content.default.yml
drupal/config/sync/field.field.paragraph.pes_content.field_qa.yml
drupal/config/sync/field.storage.paragraph.field_qa.yml

Drupal: Add Q&A for PES.

---

gatsby/package.json
gatsby/yarn.lock

gatsby/fix: updated gatbsy-plugin-sharp to latest 

---

gatsby/src/components/category-item-list/measure-area-list.tsx
gatsby/src/components/category-item-list/situation-area-list.tsx
gatsby/src/templates/measures/list.tsx
gatsby/src/templates/situations/list.tsx

fixes: https://trello.com/c/EqoejIZ4/331-v-en-verzi-se-nezv%C3%BDraz%C5%88uje-aktu%C3%A1ln%C3%AD-polo%C5%BEka-menu-ve-v%C3%BDpisu-%C5%BEivotn%C3%ADch-situac%C3%AD

gatsby/fix: situations/measures active menu item - EN version

---

drupal/web/modules/custom/covid/src/Resource/Redirects.php

Pagination links aren't added, disable pagination while we investigate the issue.

Drupal: Disable pager for Redirect resources.

---

gatsby/src/components/content-box/content-box.module.scss
gatsby/src/components/guide/guide.module.scss

Make vaccination green / white contrast WCAG AA compliant

Gatsby: fix vaccination colour contrast

---

gatsby/src/components/header/header.tsx

Fixes of the mobile menu accessibility according to https://trello.com/c/fsj1h1ml/368-a11y-p%C5%99%C3%ADstupnost-mobiln%C3%ADho-menu

Gatsby/feature: Gatsby: Mobile menu A11y fixes

---

gatsby/config/gatsby-ssr.tsx

Fix of HTML lang code with server-side rendering  according to https://trello.com/c/7PJgAx3Y/376-a11y-langcs-v-k%C3%B3du-anglick%C3%A9-str%C3%A1nky

Gatsby/feature: SSR HTML lang fix
